### ISSUE TITLE
[meta] Near future of the powerdns provider

### ISSUE THREAD

**Issue by mbag** [terraform-providers/terraform-provider-powerdns#15]
Since @splashx and I ( @mbag ) adopted this provider, we will work to make it compatible with TF v0.12.   
In order to do so, the PRs that are currently open will be merged, so that once we start working on v0.12 compatibility changes, we don't have to solve compatibility of these PRs as well. 

Once done, final version that works with Terraform v0.11 will be released and then I'll start refactoring provider code to adhere to Terraform v0.12.

**Comment by dannyk81** [comment]
@mbag @splashx thanks for your effort!

**Comment by mbag** [comment]
Today, with the help from @radeksimko  we released [v1.0.0](https://github.com/terraform-providers/terraform-provider-powerdns/releases/tag/v1.0.0). Thank you all for your patience. :tada: 

To upgrade to TF v0.12 you should follow the [Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html) to avoid any inconsistencies or problems during upgrade.

I will try to keep up the provider with the latest requirements and stay compatible with the terraform core. If you have functionality, that you would like to see in the PowerDNS provider, open an issue with description or even better, send PR that adds the functionality :wink:

**Comment by loksonarius** [comment]
Just to be perfectly clear, this provider is "certified" Terraform 0.12 compatible, yeah?
Working on some changes, and want to be sure of this

**Comment by splashx** [comment]
@loksonarius yes, this is true from [`v1.0.0`](https://github.com/terraform-providers/terraform-provider-powerdns/blob/master/CHANGELOG.md#100-august-06-2019) onwards.
