### ISSUE TITLE
Updating serial in SOA record results in error

### ISSUE THREAD

**Issue by c33s** [terraform-providers/terraform-provider-powerdns#29]
having a config like that, running `terraform apply` works.
```tf
resource "powerdns_record" "SOA_example_com" {
  zone    = "example.com."
  name    = "example.com."
  type    = "SOA"
  ttl     = 3600
  records = ["ns1.c33s.net. hostmaster.example.com. 2019090208 10800 3600 360000 300"]
}
```
the soa record is created. everything fine. changing the serial number afterwards from `2019090208` to `2019090210` and running `terraform apply` again resulting in an error.

deleting the record with sql `delete from records where id=49;` and running `terraform apply` again correctly creates the record.

i don't had the problem with version 0.1.0 of this provider but don't needed to update my config for quite a while. today i wanted to change some config and thought it would be a good thing to update. then i got this error. downgrading to 0.1.0 does not help. i have not changed my terraform config or updated terraform. i only added a zone and an a record.

### Expected Behavior
the soa record should be updated normally 

### Actual Behavior

```
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ powerdns_record.SOA_example_com (new resource required)
      id:                 "example.com.:::SOA" => <computed> (forces new resource)
      name:               "example.com." => "example.com."
      records.#:          "1" => "1"
      records.161965187:  "" => "ns1.mydns.net. hostmaster.example.com. 2019090208 10800 3600 360000 300" (forces new resource)
      records.3839120863: "ns1.mydns.net. hostmaster.example.com. 2019090206 10800 3600 360000 300" => "" (forces new resource)
      ttl:                "3600" => "3600"
      type:               "SOA" => "SOA"
      zone:               "example.com." => "example.com."


Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions in workspace "production"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

powerdns_record.SOA_example_com: Destroying... (ID: example.com.:::SOA)

Error: Error applying plan:

1 error(s) occurred:

* powerdns_record.SOA_example_com (destroy): 1 error(s) occurred:

* powerdns_record.SOA_example_com: Error deleting PowerDNS Record: Error deleting record: example.com. SOA, reason: "No SOA found for domain 'example.com.'"
```

### References
maybe related to https://github.com/PowerDNS/pdns/issues/4705

**Comment by splashx** [comment]
Can you please send the output of:

```
curl -s -H 'X-Api-Key: secret' -X GET   http://<pdns-fqdn>/api/v1/servers/localhost/zones/example.com. | jq '.soa_edit, .soa_edit_api'
```

?

**Comment by splashx** [comment]
Can you please send the output of:
```
POWERDNS_URL="localhost:8081" ; \
POWERDNS_API_KEY="secret" ; \
ZONE_NAME="example.com." ; \
curl -s \
-H "X-Api-Key: $POWERDNS_API_KEY" \
-X GET   http://${POWERDNS_URL}/api/v1/servers/localhost/zones/${ZONE_NAME} \
| jq '.soa_edit, .soa_edit_api'
```
?

**Comment by c33s** [comment]
@splashx the output you requested:

```json
  "soa_edit": "",
  "soa_edit_api": "DEFAULT",
```

i noticed that if i don't manually increase the serial, the serial gets auto increased. i always had the problem, that the replica servers don't get notified only if i manually increase the serial.

**Comment by splashx** [comment]
@c33s since you mentioned you didn’t change anything on your side but the problem appeared anyway, I assume your DNS provider upgraded the PowerDNS version, and thus the API interface is no longer the same. 

If you still wish to increase and change the SOA at will, I suggest you change the `soa_edit_api` to `””`. 

I was able to replicate your problem, and that happens only when the zone is created without explicitly defining the value for `soa_edit_api`. Since you have this set to `DEFAULT` the behavior you’re experiencing is expected. So I’ll close the issue.

If you really wish to change the serial yourself, you must change `soa_edit_api` to `””`,  as seen here:

 https://github.com/terraform-providers/terraform-provider-powerdns/blob/3d8c32c5ffe7c6e7932886a86f94d7e51f94eef9/docker-compose.yml#L47

Let me know if I’ve clarified the problem - if not we can reopen the issue. 

Cheers!

**Comment by c33s** [comment]
@splashx the powerdns server is mine, so also no changes there but as i used the old powerdns terraform provider, i had to create the zones myself. this time i created the zone with the newest version of the provider. 

thanks for the info about the `soa_edit` parameter. will play around with this setting.

would be good to have the option to define the soa_edit value in terraform.

**Comment by splashx** [comment]
@c33s thanks for the feedback. I’ve created #34 to track this issue - we will move the discussion there since I think it’s a valid concern.
