### ISSUE TITLE
Feature request: add support for resource import (zones/records)

### ISSUE THREAD

**Issue by dannyk81** [terraform-providers/terraform-provider-powerdns#31]
I think it would be great to add the ability to import resources (zones and records).

I will try to provide a working PR, since in most cases this just needs a pass-through state importer definition in the schema:
```
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
```

**Comment by dannyk81** [comment]
Have a prototype of zone import already working

configuration:
```
resource "powerdns_zone" "test_com" {
  name = "test.com."
  kind = "Master"

  nameservers = formatlist("%s.", keys(local.pdns_servers))
}
```

```
$ terraform import powerdns_zone.test_com '{"name": "test.com."}'
Acquiring state lock. This may take a few moments...
powerdns_zone.test_com: Importing from ID "{\"name\": \"test.com.\"}"...
powerdns_zone.test_com: Import prepared!
  Prepared powerdns_zone for import
powerdns_zone.test_com: Refreshing state... [id=test.com.]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

Releasing state lock. This may take a few moments...
ck. This may take a few moments...
powerdns_zone.test_com: Importing from ID "{\"name\": \"test.com.\"}"...
powerdns_zone.test_com: Import prepared!
  Prepared powerdns_zone for import
powerdns_zone.test_com: Refreshing state... [id=test.com.]

Import successful!
```

state show:
```
terraform state show powerdns_zone.test_com
# powerdns_zone.test_com:
resource "powerdns_zone" "test_com" {
    id          = "test.com."
    kind        = "Master"
    name        = "test.com."
    nameservers = [
        "pdns-01.test.com.",
        "pdns-02.test.com.",
    ]
}
```

and a plan after import:
```
powerdns_zone.novumproject_com: Refreshing state... [id=test.com.]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.
```


I'll keep working on the same for record resource and will also add tests.

**Comment by splashx** [comment]
@dannyk81 Using `schema.ImportStatePassthrough` wouldn’t  work?

**Comment by dannyk81** [comment]
@splashx indeed that was my initial attempt, but using `schema.ImportStatePassthrough` comes with a challenge: "This function requires the Read function to be able to refresh the entire resource with d.Id() ONLY." https://www.terraform.io/docs/extend/resources/import.html#importer-state-function

1) with the `zone` resource, I believe I have a working solution - however it requires changes to the `Read` and `Exists` methods, I will push this soon for you to take a look at.

2) with the `record` resource, this is tricky - since we need both the Zone name and the Record ID to be able to retrieve the RR Set.

**Comment by dannyk81** [comment]
@splashx just pushed latest changes.

1) `zone` resource uses `schema.ImportStatePassthrough`
2) tests for importing added to both

I think this is ready for a review, let me know what you think :smile:

**Comment by dannyk81** [comment]
@splashx have a question about https://github.com/terraform-providers/terraform-provider-powerdns/blob/3d8c32c5ffe7c6e7932886a86f94d7e51f94eef9/powerdns/resource_powerdns_record.go#L101

since this is deleting any record with an empty rrSet, shouldn't this line be `d.SetId("")` after a successful delete?

**Comment by splashx** [comment]
> since this is deleting any record with an empty rrSet, shouldn't this line be d.SetId("") after a successful delete?

You're right here, but the fix most likely will involve touching other places so I've opened [another issue](https://github.com/terraform-providers/terraform-provider-powerdns/issues/33) to track this.
