### ISSUE TITLE
Zones created with this provider should set “soa_edit_api” to empty?

### ISSUE THREAD

**Issue by splashx** [terraform-providers/terraform-provider-powerdns#34]
See issue #29 for details.

**Comment by c33s** [comment]
not sure if a "force" empty is the best choice. making it configureable would be good.

**Comment by splashx** [comment]
@c33s right - I think we can make that optional to avoid breaking things.

**Comment by dannyk81** [comment]
@splashx making this configurable sounds like best approach, especially since there's no default for this yet https://github.com/PowerDNS/pdns/issues/6173

In general, we set `SOA-EDIT-API` to `INCEPTION-INCREMENT`

https://doc.powerdns.com/authoritative/dnssec/operational.html#inception-increment

**Comment by splashx** [comment]
This was closed via #40
