### ISSUE TITLE
Use resource.ParallelTest instead of resource.Test

### ISSUE THREAD

**Issue by splashx** [terraform-providers/terraform-provider-powerdns#36]
References:

https://godoc.org/github.com/hashicorp/terraform/helper/resource#ParallelTest
https://godoc.org/github.com/hashicorp/terraform/helper/resource#Test

**Comment by loksonarius** [comment]
Hey, I'm kind of a scrub at Golang, so I'd like to ask for a possible example of what the work for this could look like. I've gotten almost everything working for development by following the examples in the README. The only thing I haven't gotten working are the HTTPS tests, but I still need to look into why.

Could you post an example of the kind of change to make? I found that the following files contain uses for the `testing.Test` function:

```
./powerdns/resource_powerdns_record_test.go
./powerdns/resource_powerdns_zone_test.go
```

I see that functions like `TestAccPDNSZoneNative` have a section using `TestCase` with the `Test` function, but I can't immediately tell from the `testing` docs if there's more to be done than swap `Test` with `ParallelTest` and ensure things continue working.

Are the current tests already safe to run in parallel like that? Is there more work that isn't immediately obvious?

**Comment by splashx** [comment]
@loksonarius I had something done locally and I've opened #38 which should answer your questions. It should be in `master` soon, nonetheless you can use to that branch as reference.

**Comment by loksonarius** [comment]
Just saw, thanks for the heads up. It did answer my questions 👌
