### ISSUE TITLE
Doed terraform support the Alias type for powerdns

### ISSUE THREAD

**Issue by zweizhang** [terraform-providers/terraform-provider-powerdns#41]
Hi there,

Thank you for opening an issue. 
I want to know if terraform support the ALIAS type for powerdns ,if yes, can you let me know how to configure my code ? Thanks in advance.

### Terraform Version
Terraform v0.11.7
+ provider.aws v2.38.0
+ provider.powerdns v1.2.0

### Affected Resource(s)
Can not use terraform to create alias type records for powerdns

### Terraform Configuration Files
```
resource "powerdns_record" "test" {
  zone    = "${var.powerdns_test_external_zone}"
  name    = "test.${var.powerdns_test_external_zone}"
  ttl     = 300
  type    = "ALIAS"
  records = ["xxxxxx.cloudfront.cn."]
}

```
I also change "ALIAS" to "ANAME" , it was not work.

### Debug Output
```
Error: Error applying plan:

1 error(s) occurred:

* powerdns_record.test: 1 error(s) occurred:

* powerdns_record.test: Failed to create PowerDNS Record: Error creating record set: test.test.cn.:::ACNAME, reason: "RRset test.test.cn. IN ACNAME: unknown type given"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by splashx** [comment]
The provider doesn’t validate record type, this error is coming from the PowerDNS server so I assume it doesn’t support this record type?
Refer to the PowerDNS official documentation, for example: 
https://doc.powerdns.com/authoritative/guides/alias.html

**Comment by zweizhang** [comment]
@splashx Thanks for your reply.
Our Powerdns server is support the ALIAS type, I can  add it by pdnsutil command by manually.
```
+test.test.cn 300 IN ALIAS xxxxxx.cloudfront.cn

(a)pply these changes, (e)dit again, (r)etry with original zone, (q)uit: a
Adding NSEC ordering information
root@ip-10-251-7-27:~#

```
Because our infra codes always used terraform to manage , so I hope create the ALIAS type records by terraform.

I wonder if terrform support `ALIAS` type for powerdns ?

**Comment by splashx** [comment]
@zweizhang you're using `ACNAME` as record type - that type is not supported by PowerDNS.
[Here](https://doc.powerdns.com/md/types/) is the list of all supported types. 

You probably wanted to use `ALIAS` instead of `ACNAME`?

**Comment by splashx** [comment]
What's the version of PowerDNS being used?

**Comment by splashx** [comment]
@zweizhang `ALIAS` is supported. Tested with PowerDNS 4.1 and 4.0 and the following tf definition:

```
resource "powerdns_record" "test-alias" {
 	zone = "sysa.xyz."
 	name = "alias.sysa.xyz."
 	type = "ALIAS"
 	ttl = 3600
 	records = [ "www.some-alias.com." ]
 }
```

Perhaps if you would paste the tf definition being used that would be great.

**Comment by zweizhang** [comment]
@splashx I tried it with ALIAS again and it worked now !!!
I remember I tried ALIAS before  but failed , so I changed it to  ACNAME .
Whatever, thanks so much for your help !
Have a nice day !
