### ISSUE TITLE
add master ips for slave zone

### ISSUE THREAD

**Issue by networksecadmin** [terraform-providers/terraform-provider-powerdns#53]
Hi there,

I have problems with adding ip addresses of the master dns server for a slave zone.
The only way is to add it manually in my postgresql database via:
INSERT INTO domains (name, master, type) VALUES ('test.example.de', '192.168.10.11, 192.168.10.12', 'SLAVE');

In this example my powerdns server want to become a slave of the zone test.example.de. The master of this zone is: 192.168.10.11 & 192.168.10.12

I have no opportunity to configure this scenario via terraform. I can only use:
resource "powerdns_zone" "testexamplede_zone" {
  name        = "test.example.de."
  kind        = "Slave"
  nameservers = [""]
}

Where can I add the ip addresses for the master of this zone?

Best regards
networksecadmin

**Comment by mbag** [comment]
Hello,

If you are manipulating database directly using SQL statements, and not using PowerDNS API, `terraform powerdns plugin` might not help you since it's only "middleware" that talks to PowerDNS API. 

But I'm not sure if I understand problem. Did you try doing this:
```
resource "powerdns_zone" "testexamplede_zone" {
name = "test.example.de."
kind = "Slave"
nameservers = ["192.168.10.11", "192.168.10.12"]
}
```
and got error `Nameserver is not canonical:`? 

This is the response from PowerDNS API, as it expects namesers to be FQDN i.e. `ns1.test.example.de`. So the solution is either to use FQDN for nameserver, or append dot (`.`) to your nameservers, so they bbecome `192.168.10.11.` and `192.168.10.12.`. 

I'm not sure what will happen if those IPs have dots at the end, but PowerDNS API will not complain.  I have tested against PowerDNS 4.1.10 that can be run locally, using `docker-compose.yml` found in this repo. I have used following TF file:
```
provider "powerdns" {
  api_key    = "secret"
  server_url = "http://localhost:8081/api/v1"
}

resource "powerdns_zone" "testexamplede_zone" {
  name        = "test.example.de."
  kind        = "Slave"
  nameservers = ["192.168.10.11.", "192.168.10.12."]
}
```

The result is  following, and you can check API to see zone is there: 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + powerdns_zone.testexamplede_zone
      id:                     <computed>
      kind:                   "Slave"
      name:                   "test.example.de."
      nameservers.#:          "2"
      nameservers.1709019321: "192.168.10.12."
      nameservers.1738223328: "192.168.10.11."


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

powerdns_zone.testexamplede_zone: Creating...
  kind:                   "" => "Slave"
  name:                   "" => "test.example.de."
  nameservers.#:          "" => "2"
  nameservers.1709019321: "" => "192.168.10.12."
  nameservers.1738223328: "" => "192.168.10.11."
powerdns_zone.testexamplede_zone: Creation complete after 0s (ID: test.example.de.)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Hope this helps.
Kind regards.

**Comment by networksecadmin** [comment]
Hey,

thank you for the quick reply.
I can deploy it like this:
```
powerdns_zone.testexamplede_zone: Creating...
  kind:                   "" => "Slave"
  name:                   "" => "test.example.de."
  nameservers.#:          "" => "2"
  nameservers.1709019321: "" => "192.168.10.12."
  nameservers.1738223328: "" => "192.168.10.11."
powerdns_zone.testexamplede_zone: Creation complete after 0s (ID: test.example.de.)
```

Unfortunately the master entries are still missing in the database after the terraform apply.
![grafik](https://user-images.githubusercontent.com/61842568/76062580-44a2d580-5f86-11ea-99c0-951f60189bc1.png)

I'm not really sure if "namerservers" is the right place to add the master ip addresses.
According to this page: [](https://jpmens.net/2015/01/09/a-look-at-the-powerdns-rest-api/) there is a field named "namerservers" when i am the master of a zone and there is a field named "masters" for the master ip addresses.
So the terraform code should look like this one:
```
resource "powerdns_zone" "testexamplede_zone" {
  name        = "test.example.de."
  kind        = "Slave"
  masters = ["192.168.10.11.", "192.168.10.12."]
}
```

**Comment by mbag** [comment]
OK, I understand now. Unfortunately not all properties for Zone object (https://doc.powerdns.com/authoritative/http-api/zone.html#zone) are supported by terraform PowerDNS provider at the moment. The `masters` property can be added to the record, but I can't make any promise on timeline.

**Comment by networksecadmin** [comment]
Thanks for helping!
This would be very nice and helpfully if this will work.

**Comment by mbag** [comment]
I have added masters attribute in #59  however, it's still not released. But you can clone repo, build provider and test locally to see if it works.
