### ISSUE TITLE
Support for MX-Records?

### ISSUE THREAD

**Issue by kommulu** [terraform-providers/terraform-provider-powerdns#54]
### Terraform Version
Terraform v0.12.21
+ provider.powerdns v1.3.0

### Affected Resource(s)
powerdns_record

It is not possible at the moment to create MX-records with this provider, because the priority-field can not be set.
Therefor, trying to create a mx-record results in an error.
Could this field be added to the powerdns_record resource?

**Comment by mbag** [comment]
Priority field in PowerDNS is set in the `records` field, in the example below `10 mail1.example.com.` will have priority set to `10`, `mail2.exaple.com` to `20`.
```
resource "powerdns_record" "test-mx-multi" {
	zone = "sysa.xyz."
	name = "multi.sysa.xyz."
	type = "MX"
	ttl = 60
	records = [ "10 mail1.example.com.", "20 mail2.example.com." ]
}```

Querying DNS server for MX record in the example above will return:
```
sysa.xyz.		60	IN	MX	10 mail1.example.com.
sysa.xyz.		60	IN	MX	20 mail2.example.com.
```

**Comment by kommulu** [comment]
Hi,
that worked great.
Thanks :)

PS: Would be good in the docs too.

**Comment by mbag** [comment]
Docs have been updated with this and an example on how to add mutliple records. The PR in question is here: https://github.com/terraform-providers/terraform-provider-powerdns/pull/57

It might take a while until this is visible on official terraform documentation, as they have to build the documentation pipeline for the main documentation website. But this happens a few times a day, so I hope it will propagate published soon.
