### ISSUE TITLE
masters attribute doesn't allow to specify port

### ISSUE THREAD

**Issue by maxnasonov** [terraform-providers/terraform-provider-powerdns#64]
`masters` attribute support has been added in #59 but the validation there is more strict than needed. PowerDNS supports port for master values but the resource expects only a valid IP.

### Terraform Version
v0.12.25

### Affected Resource(s)
powerdns_zone

### Terraform Configuration Files
```hcl
resource "powerdns_zone" "zone" {
  name = var.zone_name
  kind = "Slave"
  masters = ["192.168.0.1:5553"]
}
```

### Debug Output
```
Error: values in masters list attribute must be valid IPs

  on ../powerdns/zone/main.tf line 10, in resource "powerdns_zone" "zone":
  10: resource "powerdns_zone" "zone" {
```

**Comment by mbag** [comment]
Hi @maxnasonov  thanks for reporting the issue.

When implementing the feature, I used this documentation as reference https://doc.powerdns.com/authoritative/http-api/zone.html#zone but now I found out that `pdnsutil` does allow IP with optional port (https://doc.powerdns.com/authoritative/manpages/pdnsutil.1.html#zone-manipulation-commands) 

Were you able to set `masters` to `IP:port` via PowerDNS API?
